branches:
  only:
    - development
language: python
before_install:
    - pip install coveralls coverage
    - cd firefox-profiles-recovery
script:
    - coverage run -m unittest
after_success:
    - coveralls