language: python
python:
    - "3.4"
install: "pip install -r requirements.txt"
script:
    - coverage run --omit "*init*.py,test/*,*/.local/lib64/*,*/.local/lib/*,*/site-packages/*" -m unittest
    - sonar-scanner
after_success:
    - coveralls
addons:
    sonarcloud:
        organization: "rafspiny-github" # the key of the org you chose at step #3
